### PR TITLE
Add Python implementation for "Concurrent Message Processing" example

### PR DESCRIPTION
**Pull request by floscha**

### CODE REVIEW

**Review by bruth — APPROVED** [review]
@floscha Thanks for the contribution!

**Comment by bruth** [comment]
Do you mind removing the `output.txt` file? Then I will merge. The CI process generates that and the little asciicinema clip.

**Comment by floscha** [comment]
Thanks for the hint. I've removed the `output.txt` file now.

**Comment by bruth** [comment]
Thanks!

**Pull request merged**
