### PR TITLE
Add cross-region cluster use case

### PR DESCRIPTION
**Pull request by bruth**

### CODE REVIEW

**Comment by jnmoyne** [comment]
May be worth explaining that you would do this only if you won't want to create a cluster per region + 1 XR cluster and setup a meta-cluster? Maybe also explain a little bit unique_tag?

**Comment by bruth** [comment]
What would the meta cluster entail? Or how would it be used?

> Maybe also explain a little bit unique_tag?

Yes, good call out.

**Comment by jnmoyne** [comment]
Would entail one cluster per region plus a "cross region" cluster that has one node in each region all inter-connected in a super cluster (sorry I miss-typed meta cluster instead of super cluster)

**Comment by bruth** [comment]
@jnmoyne added #51 and updated some of the comments to be more helpful.

**Comment by jnmoyne** [comment]
LGTM

**Pull request merged**
