### PR TITLE
Add Python implementation of Object Storage Intro 

### PR DESCRIPTION
**Pull request by RothAndrew**

### CODE REVIEW

**Comment by RothAndrew** [comment]
I could use a bit of help figuring out how to make the `output.cast` and `output.txt` files, but otherwise I'm pretty happy with how it came out. PTAL.

**Comment by bruth** [comment]
Hey @RothAndrew! By default, the `output.*` files are generated and auto-committed by the CI process if not present for an example. However, you can choose to run `nbe generate recording` which will generate these files locally.

**Comment by RothAndrew** [comment]
Gotcha. Okay I think this is ready then.

**Review by wallyqs — APPROVED** [review]
example itself, LGTM

**Review by bruth — APPROVED** [review]

**Pull request merged**
